name: 'Reviewer lottery'
description: 'Automatically assign reviewers to Pull Requests'
author: 'Unai Esteibar'
inputs:
  repo-token:
    description: "Github token secret"
    required: true
  config:
    description: 'Path to config file'
    default: '.github/reviewer-lottery.yml'
runs:
  using: 'node12'
  main: 'dist/index.js'
