name: 'Reviewer lottery'
description: 'Automatically assign reviewers to Pull Requests'
author: 'Unai Esteibar'
inputs:
  repo-token:
    description: "Github token secret"
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
